// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDsa6I2oTP7cBN61W7KDQeaBkFDKPOKZbQ',
    appId: '1:401593830927:web:8f5f2ae181df551d5b1d7a',
    messagingSenderId: '401593830927',
    projectId: 'reddit-clone-c2742',
    authDomain: 'reddit-clone-c2742.firebaseapp.com',
    storageBucket: 'reddit-clone-c2742.firebasestorage.app',
    measurementId: 'G-J1LCR913VC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA2XGznJXYe5tJQkG8s4iUiaUzPhgdv_Ao',
    appId: '1:401593830927:android:fd9bb86b01037ba35b1d7a',
    messagingSenderId: '401593830927',
    projectId: 'reddit-clone-c2742',
    storageBucket: 'reddit-clone-c2742.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDsa6I2oTP7cBN61W7KDQeaBkFDKPOKZbQ',
    appId: '1:401593830927:web:f117b421bc34ca945b1d7a',
    messagingSenderId: '401593830927',
    projectId: 'reddit-clone-c2742',
    authDomain: 'reddit-clone-c2742.firebaseapp.com',
    storageBucket: 'reddit-clone-c2742.firebasestorage.app',
    measurementId: 'G-7LCL95DB87',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBOCE6_2dgIeLK1cRtw-VEUmO--7egUPsI',
    appId: '1:401593830927:ios:8ef338ec0e62a0315b1d7a',
    messagingSenderId: '401593830927',
    projectId: 'reddit-clone-c2742',
    storageBucket: 'reddit-clone-c2742.firebasestorage.app',
    iosBundleId: 'com.example.redditClone',
  );

}